### PR TITLE
Update release script for new Gutenberg iOS setup

### PR DESCRIPTION
**Pull request by mokagio**
See https://github.com/wordpress-mobile/WordPress-iOS/pull/20632

I tested this by copying the new lines in a script in the WordPress-iOS repo and running it.

```sh
#!/bin/bash -eu
# test.sh

MOBILE_REPO='mobile_repo_name'
GB_MOBILE_PR_REF='gb_ref'

version_file="Gutenberg/version.rb"
test -f "$version_file" || abort "Error: Could not find $version_file"
sed -i'.orig' -E "s/GITHUB_ORG = 'wordpress-mobile'/GITHUB_ORG = '$MOBILE_REPO'/" $version_file || abort "Error: Failed updating GitHub organization in $version_file"
sed -i'.orig' -E "s/# commit: '(.*)',/commit: '$GB_MOBILE_PR_REF'/" $version_file || abort "Error: Failed updating gutenberg ref in $version_file (part 1 of 2, setting the commit)"
sed -i'.orig' -E "s/tag: '(.*)'/# &/" $version_file || abort "Error: Failed updating gutenberg ref in $version_file (part 2 of 2, commenting the tag)"
```

The result was 

```diff
diff --git a/Gutenberg/version.rb b/Gutenberg/version.rb
index c1b15043b2..01bbbb7b92 100644
--- a/Gutenberg/version.rb
+++ b/Gutenberg/version.rb
@@ -11,9 +11,9 @@
 #
 #   LOCAL_GUTENBERG=../my-gutenberg-fork bundle exec pod install
 GUTENBERG_CONFIG = {
-  # commit: '',
-  tag: 'v1.94.0'
+  commit: 'gb_ref'
+  # tag: 'v1.94.0'
 }
 
-GITHUB_ORG = 'wordpress-mobile'
+GITHUB_ORG = 'mobile_repo_name'
 REPO_NAME = 'gutenberg-mobile'
```

Let me know if it looks good and appropriate for your workflow.

### CODE REVIEW

**Comment by jhnstn** [comment]
Hey @mokagio  I just noticed https://github.com/wordpress-mobile/WordPress-iOS/pull/20632 via this PR. 

I'm wondering if you would consider using JSON for the version data in `Gutenberg/version.rb` ? It would really help simplify how we automate updating the Gutenberg version. 

Here is a quick sketch of what I'm thinking:  https://github.com/wordpress-mobile/WordPress-iOS/compare/trunk...try/gutenberg-json-config

Then we can use `jq` to update the version, something like:

```bash
#!/bin/bash -eu
GB_MOBILE_PR_REF="1234"

ios_gb_version_json=${IOS_DIR}/Gutenberg/version.json

jq --arg commit $GB_MOBILE_PR_REF  \
'del(.config.tag) | . * {"config":{"commit": $commit}} ' \
 $ios_gb_version_json | sponge $ios_gb_version_json

```
(NOTE: I'm not sure why we allow pointing to a different Gutenberg Mobile repo during a release. I know those variables are there for testing out the release script but I'm not sure why we, even during testing, that we would need to have the iOS repo point to some alternative Gutenberg Mobile repo. Ether way we can use `jq` to update the repo if needed. )


I did notice this comment in the `Gutenberg/version.rb`:

> This way, it can be accessed by multiple sources without duplication.

Not sure if you have plans to source that ruby file someplace else but I would think JSON would be compatible with most scripts.

Feel free to drop the JSON suggestion but I figured I'd bring it up since I might be refactoring the gutenberg mobile release automation script soon.

**Review by jhnstn — APPROVED** [review]
The changes look good. Feel free to merge this unless you are interested in the json route I suggested.
Thanks!

**Comment by mokagio** [comment]
Thank you @jhnstn. I'm going to merge this because [the WordPress iOS counterpart auto-merged](https://github.com/wordpress-mobile/WordPress-iOS/pull/20632) and I want this script to be usable on `trunk`.

I love the idea of using a more readable format for the config. What do you think of using YAML instead? I prefer YAML over JSON for configurations because it allows to write comments. There is also a `jq` equivalent for YAML called [`yq`](https://kislyuk.github.io/yq/).

**Comment by dcalhoun** [comment]
> I'm not sure why we allow pointing to a different Gutenberg Mobile repo during a release. I know those variables are there for testing out the release script but I'm not sure why we, even during testing, that we would need to have the iOS repo point to some alternative Gutenberg Mobile repo.

I believe separate repository support was added to avoid creation of temporary branches, tags, etc while testing the script. If those were created in the primary repository, one would feel the need to clean up. An additional benefit is for new members who do not yet have write access to the primary repository, new members can test running the script with their own forks; this may be a less common scenario, but one that I took advantage of before my first release.

**Comment by fluiddot** [comment]
Heads up that I've run the release script for version `1.95.0` and the file `Gutenberg/version.rb` ~~hasn't been updated~~ has been updated but wasn't committed. Was it working when you tested these changes @jhnstn @mokagio?

**UPDATE:** Fix created in https://github.com/wordpress-mobile/release-toolkit-gutenberg-mobile/pull/115.

**Comment by jhnstn** [comment]
> I love the idea of using a more readable format for the config. What do you think of using YAML instead? I prefer YAML over JSON for configurations because it allows to write comments. There is also a jq equivalent for YAML called [yq](https://kislyuk.github.io/yq/).

@mokagio YAML is great. I was actually feeling the lack of comments in JSON when I put together that other patch 😄  TIL about `yq`, thanks!

**Comment by mokagio** [comment]
> Was it working when you tested these changes @jhnstn @mokagio?

I wasn't game for running the release script and only tested the update logic by copying the new lines in a script in the WordPress-iOS repo and running it, which worked.

Sorry for the trouble @fluiddot

**Comment by fluiddot** [comment]
> > Was it working when you tested these changes @jhnstn @mokagio?
> 
> I wasn't game for running the release script and only tested the update logic by copying the new lines in a script in the WordPress-iOS repo and running it, which worked.
> 
> Sorry for the trouble @fluiddot

@mokagio No worries at all, it's tricky to test the entire script. The final test of script changes usually happens when cutting a new release 🙂.

**Comment by mokagio** [comment]
> @mokagio No worries at all, it's tricky to test the entire script. The final test of script changes usually happens when cutting a new release 🙂.

Thanks @fluiddot. For what it's worth, that's the same experience we've had with the mobile apps releases.

**Pull request merged**
