### PR TITLE
Cli/gbm patch

### PR DESCRIPTION
**Pull request by jhnstn**
Depends on #212 and #213

Adds patch support to preparing Gutenberg Mobile patch releases

### Pre-steps
Using forks of Gutenberg and Gutenberg Mobile:
-  If you don't have one already one, create a "scheduled" release on both Gutenberg and Gutenberg Mobile via `prepare all`
- Merge both of the release prs 
- Create a Github release on the Gutenberg Mobile fork repo for the release created in the former step 

--- 

- Create a patch for a release PR  on the forked Gutenberg repo ( no need to merge )
- Run the `release prepare gbm {patch-version} --keep` command
- Expect a prompt to edit/review the release notes in Gutenberg Mobile
- Confirm creating the PR
- After the script run cd into the temp directory and verify the git reflog shows the release branch starts from the previous release tag

Note: the first two steps can be accomplished by running the `prepare all` command with the patch release version

### CODE REVIEW

**Review by derekblank — COMMENTED** [review]
When running `prepare all` with the `--keep` flag, I received this error with fetching pnpm. Just wanted to check if it was expected or not:

```
Update "react-native-editor" package i18n cache
/var/folders/xk/xmtl5xjx33v_bp94749wm0j00000gn/T/gbm-711427600/gbm/jetpack /var/folders/xk/xmtl5xjx33v_bp94749wm0j00000gn/T/gbm-711427600/gbm
Found '/var/folders/xk/xmtl5xjx33v_bp94749wm0j00000gn/T/gbm-711427600/gbm/jetpack/.nvmrc' with version <18.13.0>
v18.13.0 is already installed.
Now using node v18.13.0 (npm v8.19.3)
npm ERR! code FETCH_ERROR
npm ERR! errno FETCH_ERROR
npm ERR! invalid json response body at https://registry.npmjs.org/pnpm reason: Invalid response body while trying to fetch https://registry.npmjs.org/pnpm: ENOENT: no such file or directory, stat '/tmp/empty-cache/_cacache/content-v2/sha512/c4/73/fe4f21c6ba889cc4c7f4621c69a114e71fad9cc3907d9f016258acffb9e1fd83f15d77a039b3351bda73c3b499ec9a2c6e5d963d96aed8e11b0cf54b2bad'

npm ERR! A complete log of this run can be found in:
npm ERR!     /tmp/empty-cache/_logs/2023-11-07T00_01_06_981Z-debug-0.log
npm ERR! code 1
npm ERR! path /private/var/folders/xk/xmtl5xjx33v_bp94749wm0j00000gn/T/gbm-711427600/gbm
npm ERR! command failed
npm ERR! command sh -c -- patch-package && npm run clean:gutenberg:distclean && npm ci --prefix gutenberg && npm run i18n:check-cache && ./bin/run-jetpack-command.sh "install --ignore-scripts"

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/derekblank/.npm/_logs/2023-11-06T23_59_56_199Z-debug-0.log
[ERROR] error running npm ci: exit status 1
```

**Comment by jhnstn** [comment]
> When running `prepare all` with the `--keep` flag, I received this error with fetching pnpm. Just wanted to check if it was expected or not:
> 
> ```
> Update "react-native-editor" package i18n cache
> /var/folders/xk/xmtl5xjx33v_bp94749wm0j00000gn/T/gbm-711427600/gbm/jetpack /var/folders/xk/xmtl5xjx33v_bp94749wm0j00000gn/T/gbm-711427600/gbm
> Found '/var/folders/xk/xmtl5xjx33v_bp94749wm0j00000gn/T/gbm-711427600/gbm/jetpack/.nvmrc' with version <18.13.0>
> v18.13.0 is already installed.
> Now using node v18.13.0 (npm v8.19.3)
> npm ERR! code FETCH_ERROR
> npm ERR! errno FETCH_ERROR
> npm ERR! invalid json response body at https://registry.npmjs.org/pnpm reason: Invalid response body while trying to fetch https://registry.npmjs.org/pnpm: ENOENT: no such file or directory, stat '/tmp/empty-cache/_cacache/content-v2/sha512/c4/73/fe4f21c6ba889cc4c7f4621c69a114e71fad9cc3907d9f016258acffb9e1fd83f15d77a039b3351bda73c3b499ec9a2c6e5d963d96aed8e11b0cf54b2bad'
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /tmp/empty-cache/_logs/2023-11-07T00_01_06_981Z-debug-0.log
> npm ERR! code 1
> npm ERR! path /private/var/folders/xk/xmtl5xjx33v_bp94749wm0j00000gn/T/gbm-711427600/gbm
> npm ERR! command failed
> npm ERR! command sh -c -- patch-package && npm run clean:gutenberg:distclean && npm ci --prefix gutenberg && npm run i18n:check-cache && ./bin/run-jetpack-command.sh "install --ignore-scripts"
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /Users/derekblank/.npm/_logs/2023-11-06T23_59_56_199Z-debug-0.log
> [ERROR] error running npm ci: exit status 1
> ```

Hmm, that's a new one to me. I wonder if it was just momentary? I know I have run into network glitches running the release commands in the past. They usually succeed when trying again.

Also this could be a novel issue considering it's Jetpack related. For sure not the first time our stuff starts breaking after changes on Jetpack.

**Comment by jhnstn** [comment]
@derekblank I ran into the same error but it seems to be working now.  

I tried to find more info about the error to see if anyone else was facing the same issue. I couldn't find any recent reports. Fingers crossed it's resolved.

Do you mind given this another try? If it pops up again try again on trunk. I have a feeling it's not related to the changes in this PR.

**Comment by derekblank** [comment]
> Do you mind given this another try? If it pops up again try again on trunk. 

Yep, I'll give it another go.

**Review by derekblank — APPROVED** [review]
Success this time with running `prepare all` with the `--keep` flag:

```
[INFO] Finished preparing Gutenberg Mobile PR
[INFO] 
Finished preparing PRs:
https://github.com/derekblank/gutenberg/pull/30
https://github.com/derekblank/gutenberg-mobile/pull/9
[INFO] Keeping temporary directory /var/folders/xk/xmtl5xjx33v_bp94749wm0j00000gn/T/gbm-1558918830
[INFO] Keeping temporary directory /var/folders/xk/xmtl5xjx33v_bp94749wm0j00000gn/T/gbm-1558918830
```

Must've been a temporary Jetpack breakage, as you stated, as I didn't make any other changes to my environment on my end besides just re-running.

LGTM! 🚀

**Pull request merged**
