### PR TITLE
Add Gitignore file and ignore macOS finder files

### PR DESCRIPTION
**Pull request by twstokes**
- Add a `.gitignore` to the repo
- Ignore macOS Finder `.DS_Store` files
- Ignore VSCode local config files

### CODE REVIEW

**Comment by twstokes** [comment]
Hey @fluiddot, I chose you randomly for this little PR if you don't mind taking a look! 🙇‍♂️

**Review by fluiddot — APPROVED** [review]
LGTM 🎊 !

I'm wondering if we should also add some of the patterns that we have in the GB-mobile repo ([reference](https://github.com/wordpress-mobile/gutenberg-mobile/blob/develop/.gitignore)) 🤔 , although since we only have scripts here most of them don't apply except the VSCode:
```
# VSCode local config dir
.vscode/*
!.vscode/settings.json
!.vscode/tasks.json
!.vscode/launch.json
!.vscode/extensions.json
```

**Comment by twstokes** [comment]
> I'm wondering if we should also add some of the patterns that we have in the GB-mobile repo

Good thinking @fluiddot! I've added those to this PR.

**Review by fluiddot — APPROVED** [review]
> Good thinking @fluiddot! I've added those to this PR.

Awesome, thanks for adding them ❤️ .

**Pull request merged**
