### PR TITLE
Add a clean-up step to close the release milestone

### PR DESCRIPTION
**Pull request by guarani**
Adds a clean-up step to close the release milestone. I added at the earliest point in the release after the main app builds have been cut.

### CODE REVIEW

**Comment by guarani** [comment]
@geriux, would it make sense to move this to an earlier stage? Like as soon as we cut the Gutenberg Mobile release on Thursday? My thinking is yes, but want to double-check with you.

**Comment by geriux** [comment]
> @geriux, would it make sense to move this to an earlier stage? Like as soon as we cut the Gutenberg Mobile release on Thursday? My thinking is yes, but want to double-check with you.

I agree! I think we could move it, it makes sense to close it around that time 👍

**Comment by guarani** [comment]
Thanks! I've updated the PR and it's again ready for review.

**Review by geriux — APPROVED** [review]
LGTM! Thanks for adding this 🚀

**Comment by guarani** [comment]
Thanks for the review!

**Pull request merged**
